### ISSUE TITLE
bootstrap/bootstrapAll not executed when using run-workers parameter

### ISSUE THREAD

**Issue by cwolf24** [codeceptjs/CodeceptJS#2309] opened 2020-04-02 08:59 UTC
#### What are you trying to achieve?
I want to run my tests in parallel with `run-workers` but the functions i have defined in a bootstrap/bootstrapAll file are not executed beforehand and therefor all my tests are failing.

#### What do you get instead?
When i run `codeceptjs run-workers 3 -c codecept.conf.js` there is no output from the console.log inside the bootstrap/bootstrapAll functions. (so they are not executed at all)

Additional info: when i run `codeceptjs run-multiple parallel -c codecept.conf.js` with the same bootstrap file + codeceptjs config, the output from the console.log in the bootstrap file is printed correct.

> Provide bootstrap & codecept.conf.js file content:

```js
// bootstrap file:
module.exports = {

  bootstrapAll: async function(done) {
    console.log("within bootstrapAll");
    done();
  },
  bootstrap: async function(done) {
    console.log("within bootstrap");
    done();
  }
};
```

```js
//codecept.conf.js (relevant part):
 bootstrapAll: "../bootstrap/prepareDataResources.js",
  bootstrap: "../bootstrap/prepareDataResources.js",
  multiple: {
    parallel: {
      chunks: 20
    }
  },
```

### Details

* CodeceptJS version: tested with 2.4.3 & 2.6.0
* NodeJS Version: v12.10.0
* Operating System: MacOS Catalina (10.15.3)
* Configuration file: see above

**Comment by pablopaul** [comment] 2020-04-02 09:10
@PeterNgTr would you mind to have a look here?

**Comment by PeterNgTr** [comment] 2020-04-02 10:16
The run-worker is reworking, I’m not sure if we‘d better to wait for it.

**Comment by pablopaul** [comment] 2020-04-02 10:31
> The run-worker is reworking, I’m not sure if we‘d better to wait for it.

ah right, thanks!

@chwolf please try with the branch "improved-workers" of the CodeceptJS repository, maybe its already fixed there, see https://stackoverflow.com/a/50734317/1744768

**Comment by chwolf** [comment] 2020-04-02 13:41
@pablopaul, @PeterNgTr 
I tried it now with the "improved-workers" branch, but still see the same issue, that the bootstrap an bootstrapAll is not executed at all.

In the related code i see that only the bootstrapAll is added to the recorder.
https://github.com/Codeception/CodeceptJS/blob/improved-workers/lib/workers.js#L283

and in the https://github.com/Codeception/CodeceptJS/blob/improved-workers/lib/command/run-workers.js file, no bootstrap at all is mentioned.

**Comment by PeterNgTr** [comment] 2020-04-02 14:23
@chwolf I saw the bootstrap is called here https://github.com/Codeception/CodeceptJS/blob/improved-workers/lib/command/workers/runTests.js#L48

**Comment by PeterNgTr** [comment] 2020-04-02 14:56
```js
....
  bootstrap: (done) => {
    console.log("bootstrap is called");
      done();
  },
  teardown: (done) => {
    console.log("teardown is called");
    done();
  },
....
```

@chwolf the bootstrap and teardown are called when I ran with `--verbose`

```sh
MBP-Thanh-Home:amazon-ui-tests thanhnguyen$ npx codeceptjs run-workers 1 --grep @test --verbose
DEPRECATION NOTICE:
You are using webdriverio v5. It is recommended to update to webdriverio@6.
Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

CodeceptJS v2.6.0
Running tests in 1 workers...

DEPRECATION NOTICE:
You are using webdriverio v5. It is recommended to update to webdriverio@6.
Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

4
bootstrap is called
CodeceptJS v2.6.0
Using test root "/Users/thanhnguyen/Desktop/amazon-ui-tests"
Helpers: WebDriver
[1] Search functionality --
Plugins: screenshotOnFail

Search functionality --
    [1] Starting recording promises
    Emitted | suite.before ([object Object])
  Search function is displayed @test
    Emitted | test.before ([object Object])
    Emitted | hook.start ([object Object])
    Emitted | step.before (I am on page "/")
    Emitted | step.after (I am on page "/")
    Emitted | step.start (I am on page "/")
    I am on page "/"
    Emitted | step.passed (I am on page "/")
    Emitted | step.finish (I am on page "/")
    Emitted | hook.passed ([object Object])
    Emitted | test.start ([object Object])
    Emitted | step.before (I dont see element "#twotabsearchtextbox")
    Emitted | step.after (I dont see element "#twotabsearchtextbox")
    Emitted | step.before (I see element "input[type="submit"]")
    Emitted | step.after (I see element "input[type="submit"]")
    Emitted | step.start (I dont see element "#twotabsearchtextbox")
    I dont see element "#twotabsearchtextbox"
    [1] Error | Error
[1]   ✖ Search function is displayed @test in 160ms
    Emitted | step.failed (I dont see element "#twotabsearchtextbox")
    Emitted | step.finish (I dont see element "#twotabsearchtextbox")
    [1] Error | Error
    Emitted | step.failed (I see element "input[type="submit"]")
    Emitted | step.finish (I see element "input[type="submit"]")
    [1] Error | Error
    [1] Starting <teardown> session
    Emitted | test.failed ([object Object])
    Emitted | test.finish ([object Object])
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, saving screenshot
 › Screenshot has been saved to /Users/thanhnguyen/Desktop/amazon-ui-tests/output/Search_fun_1585839218.failed.png
  ✖ FAILED in 865ms

    [2] Starting recording promises
    Emitted | test.after ([object Object])
    Emitted | suite.after ([object Object])

-- FAILURES:

  1) Search functionality
       Search function is displayed @test:
     expected elements of #twotabsearchtextbox not to be seen
  
  Scenario Steps:
  
  - I.dontSeeElement("#twotabsearchtextbox") at Test.<anonymous> (tests/search/search_tests.js:10:7)
  
  


  FAIL  | 0 passed, 1 failed   // 5s
teardown is called
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])


-- FAILURES:

  1) Search functionality
       Search function is displayed @test:
     expected elements of #twotabsearchtextbox not to be seen
  
  Scenario Steps:
  
  - I.dontSeeElement("#twotabsearchtextbox") at Test.<anonymous> (/Users/thanhnguyen/Desktop/amazon-ui-tests/tests/search/search_tests.js:10:7)
```

**Comment by PeterNgTr** [comment] 2020-04-08 08:03
@chwolf could you check if it's still an issue for you or we can close this?

**Comment by chwolf** [comment] 2020-04-08 09:51
@PeterNgTr For me it still does not work at all. 
When i run our tests with `run-multiple  parallel --verbose` i see the console.log output from my bootstrap function before the first verbose output: `[1] Starting recording promises ` output. See log:
```
npx codeceptjs run-multiple parallel -c configs/codecept.conf.js --verbose

inside bootstrap readApiDoc
inside bootstrap readApiDoc
inside bootstrap readApiDoc
inside bootstrap createResources
inside bootstrap createResources
inside bootstrap createResources
[2.parallel:chunk2:chrome] CodeceptJS v2.5.0
[2.parallel:chunk2:chrome] Using test root "/test"
[2.parallel:chunk2:chrome] Helpers: WebDriver, REST, CustomActions
[2.parallel:chunk2:chrome] Plugins: screenshotOnFail

[2.parallel:chunk2:chrome] Generic Api --
```
[2.parallel:chunk2:chrome]     [1] Starting recording promises
...

When i run the same with `run-workers 3` parameter instead of `run-multiple` no console.log from the bootstrap function nor any verbose output is printed, because it will fail immediately because the bootstrap function is not called. Within the bootstrap we parse an API doc before anything because this will be used to create a DataTable out of the API doc for a DDT scenario. This fails before any suite is started because the bootstrap is not called at all. 

This is our Bootstrap function:
```
const SwaggerParser = require("swagger-parser");
const apiReferenceFile = "./data/genericApiReference.yaml";
const { CustomActions } = require("codeceptjs").container.helpers();

async function readApiDoc() {
  console.log("inside bootstrap readApiDoc");
  const apiDoc = await SwaggerParser.dereference(apiReferenceFile);

  codeceptjs.container.append({
    support: { apiDoc }
  });
}

async function createResources() {
  console.log("inside bootstrap createResources");
  const createdResources = await CustomActions.createResources();
  codeceptjs.container.append({
    support: { createdResources }
  });
}

module.exports = async function(done) {
  await readApiDoc();
  await createResources();
  done();
};
```
Is there something wrong with it?

**Comment by PeterNgTr** [comment] 2020-04-08 13:24
well, @chwolf, I thought  providing a repo to reproduce this issue would be nice. :)

**Comment by richardhendricksen** [comment] 2020-04-15 08:02
I'm experiencing the same issue. I have a Bootstrap file that registers tsConfigPaths for my Typescript files. When I run with `npx codeceptjs run --verbose`, then there is no issue and the bootstrap code is called:
```
------------in bootstrap---------
CodeceptJS v2.5.0
Using test root "/Users/richard/code/malmberg/Project-P1-Leerling-App/apps/p1-it-new"
Helpers: TestCafe, TestCafeHelper
Plugins: screenshotOnFail, allure
...
```

When running with `run-workers 2` however, the code immediately fails cause of the Bootstrap file not loading:
```
CodeceptJS v2.5.0
Running tests in 2 workers...

Cannot find module '@mocking'
Require stack:
...
```
The module cannot be found because tsConfigPaths is not registered.

My config:
```
exports.config = {
  name: 'p1-it-new',
  tests: './specs/**/*.it-spec.ts',
  output: './output',
  bootstrapAll: "./setup/tsConfigPaths.js",
  bootstrap: "./setup/tsConfigPaths.js",
  include: {
    I: './helpers/customSteps.helper.ts'
  },
  helpers: {
    TestCafe: {
      url: 'http://localhost:9091',
      browser: 'chrome',
      show: true,
      restart: false
    },
    TestCafeHelper: {
      require: './helpers/testcafe.helper.js'
    }
  },
  plugins: {
    retryFailedStep: {
      enabled: false
    },
    screenshotOnFail: {
      enabled: true
    },
    allure: {
      enabled: true
    }
  },
  // require modules
  require: ["ts-node/register"]
};
```

The Bootstrap file:
```
console.log('------------in bootstrap---------');

const tsConfig = require("../tsconfig.json");
const tsConfigPaths = require("tsconfig-paths");

const baseUrl = "./";
tsConfigPaths.register({
  baseUrl,
  paths: tsConfig.compilerOptions.paths
});
```

I also tried the `improved-workers` branch as mentioned above, but I still experienced the same issue.

**Comment by chwolf** [comment] 2020-04-16 10:11
@PeterNgTr sorry, i did not think about providing a repo - which would it make easier to investigate... i will create a repo when i find some time. Thanks

**Closed** 2021-09-05 17:06 UTC

**Comment by nikhilbisht-thomann** [comment] 2024-02-08 12:14
Is this issue resolved, i am facing the similar issue
